// add this to data.copypastas
/*
"I sexually Identify as go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there. Ever since I was a boy I dreamed of ƽaүing so my self 💯 i say so💯💯. People say to me that a person being mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit is Impossible and I'm fucking retarded but I don't care. I'm having doctors inject me with (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ), go౦ԁ sHit, and mMMMMᎷМ💯. From now on I want you guys to call me \"👌👀👌👀👌👀👌👀👌👀\" and respect my right to (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ), and mMMMMᎷМ💯 👌👌 👌. If you can't accept me you're a goodshitophobe and need to check your if i do ƽaү so my self 💯 privilege. Thank you for being so understanding👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌.",

"🍣🍤🍣 IT'S SUSHI TIME🍙🍘🍣 You have been visited by the legendary Hiroshi, master of sushi 🍙🍣🍣🍥🍤 Upmoshi this within 3 seconds or you'll never have sushi without wasabi 🍣🍤🍤 ",
*/

var data = {
    copypastas: [
        "What the fuck did you just fucking say about me, you little shit? Ill have you know I graduated top of my class in the Navy Seals, and Ive been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and Im the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. Youre fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and thats just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little clever comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldnt, you didnt, and now youre paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. Youre fucking dead, kiddo.",

        "What the procreate did you just fornicating say about me, you little hallion? I’ll have you cognize I graduated most elite in my division in the Navy Seals, and I’ve been enmeshed in multifarious undisclosed incursions on Al-Quaeda, and I have over 300 habituated executions. I am experienced in guerilla campaign and I’m the most qualigied sharpshooter in the full US armed forces. You are nothing to me but just an additional victim. I will obliterate you the copulate out with rigor the likes of which has at no time been seen previously on this macrocosm, indicate my fricking units of language. You assume you can be acquit with saying that fecal matter to me via the Information Superhighway? Acknowledge anew, undesirable person. At the time that we communicate I am influencing my covert organization of operatives crosswise the New World and your Internet Protocol is being pursued immediately so you better bolster for the assault, larval fly. The disturbance that annihilates the deplorable petty existence you refer to as your duration. You’re frigging late, child under the age of 18. I can be omnipresent, at any unspecified point in time, and I can annihilate you in surplus seven centum techniques, and that’s merely with my unequipped metacarpus. Not exclusively am I extensively qualified for hand-to-hand combat, but I have admittance to the total armory of the United States Marine Corps and I will handle it to its absolute breadth to decimate your wrethed derriere off the surface of the large landmass, you minuscule excrement. If only you could have been aware of what unhallowed comeuppance your smol “ingenious” statement was almost to bear downward upon you, perchance you bequest have refrained from unpleasantly speaking. However, you couldn’t, you didn’t, and now you’re reconciling, you accursed tomfool. I will excrete acrimony all over you and you will inundate in it. You’re flipping ending, main character of Kill Bill.",

        "Okay, so you expect me to believe that you were the very best that your generation of Navy SEALs had to offer? I highly doubt that. If you were as good as you say you were, I don't think for a second that you would be browsing 4chan. This is mostly a place for jobless neckbeards that still live with their parents, and nerdy high school kids that don't have any friends. It really isn't the place for highly-trained assassins to be hanging out in their spare time. Even if it was, something far worse than a troll being mean to you probably would have set you off a long time ago. What about the slew of gore and child pornography that gets posted here on a regular basis? Isn't that something that deserves a person being hunted down and made to regret their actions? Yeah, you're just not the 4chan type. Sure, there's a wide variety of people that browse here, but you're far from the core demographic if you are who you say you are (which isn't the case). Even if it were true that you're an incredibly talented soldier, I think all the military discipline would prevent you from getting mad enough to murder some random idiot on the internet. I also doubt that even the best SEALs have a \"secret network of spies across the USA\". Why would all of the most expanisive Big Brother network in the world be willing to help a troubled PTSD-sufferer hunt down some random kid on the internet? That doesn't even make sense. If you're gonna try to scare somebody, make it more believable than \"IM A SUPER SOLDIER HURR DURR\". You might frighten a thirteen year old who doesn't know any better, but to most of us you just look like a kid with an anger problem and a very active imagination. Hopefully things will be easier for you when your puberty's over. Best of luck with that... kiddo.",

        "I sexually Identify as go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there. Ever since I was a boy I dreamed of ƽaүing so my self 💯 i say so💯💯. People say to me that a person being mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit is Impossible and I'm fucking retarded but I don't care. I'm having doctors inject me with (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ), go౦ԁ sHit, and mMMMMᎷМ💯. From now on I want you guys to call me \"👌👀👌👀👌👀👌👀👌👀\" and respect my right to (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ), and mMMMMᎷМ💯 👌👌 👌. If you can't accept me you're a goodshitophobe and need to check your if i do ƽaү so my self 💯 privilege. Thank you for being so understanding👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌.",

        "🍣🍤🍣 IT'S SUSHI TIME🍙🍘🍣 You have been visited by the legendary Hiroshi, master of sushi 🍙🍣🍣🍥🍤 Upmoshi this within 3 seconds or you'll never have sushi without wasabi 🍣🍤🍤 ",

        "Da FitnessGram™ Pacer Test be a multistage aerobic capacitizzle test dat progressively gets mo' hard as fuck as it continues. Da 20 meta pacer test will begin up in 30 seconds. Line up all up in tha start. Da hustlin speed starts slowly yo, but gets fasta each minute afta you hear dis signal. [beep] A single lap should be completed each time you hear dis sound. Y'all KNOW dat shit, muthafucka! [ding] Remember ta run up in a straight line, n' run as long as possible. Da second time you fail ta complete a lap before tha sound, yo' test is over n' shit. Da test will begin on tha word start. On yo' mark, git ready, start.﻿",

        "The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.",

        "They targeted gamers. Gamers. We're a group of people who will sit for hours, days, even weeks on end performing some of the hardest, most mentally demanding tasks. Over, and over, and over all for nothing more than a little digital token saying we did. We'll punish our selfs doing things others would consider torture, because we think it's fun. We'll spend most if not all of our free time min maxing the stats of a fictional character all to draw out a single extra point of damage per second. Many of us have made careers out of doing just these things: slogging through the grind, all day, the same quests over and over, hundreds of times to the point where we know evety little detail such that some have attained such gamer nirvana that they can literally play these games blindfolded. Do these people have any idea how many controllers have been smashed, systems over heated, disks and carts destroyed 8n frustration? All to latter be referred to as bragging rights? These people honestly think this is a battle they can win? They take our media? We're already building a new one without them. They take our devs? Gamers aren't shy about throwing their money else where, or even making the games our selves. They think calling us racist, mysoginistic, rape apologists is going to change us? We've been called worse things by prepubescent 10 year olds with a shitty head set. They picked a fight against a group that's already grown desensitized to their strategies and methods. Who enjoy the battle of attrition they've threatened us with. Who take it as a challange when they tell us we no longer matter. Our obsession with proving we can after being told we can't is so deeply ingrained from years of dealing with big brothers/sisters and friends laughing at how pathetic we used to be that proving you people wrong has become a very real need; a honed reflex. Gamers are competative, hard core, by nature. We love a challange. The worst thing you did in all of this was to challange us. You're not special, you're not original, you're not the first; this is just another boss fight."
    ],

    emails: [
        "<p>Thank you so much for contacting me about your project. While it’s true that I’ve worked in several startups and know a lot of really talented software engineers, all of them are currently working. I find that’s true for just about everyone you want – great people find ways to be busy.</p><p>I totally understand that you’re looking for folks to bring on at the ground floor and want my advice on how to find great software engineers (at a low cost). Here’s the thing – doesn’t everyone want great software engineers at a low cost? So I suggest you adjust your pitch. Look for great engineers that want to solve the problem you’re solving. Look for folks who may be busy but are passionate about your space – that may woo them away from their current efforts.</p><p>Anyway, that’s my advice and unfortunately I don’t know of a perfect fit for your project that I could recommend right now.</p><p>Thanks,<br>Chris</p>",

        "<p>Dear Sam,</p><p>As I was looking through my drafts, I realized I had never [emailed/responded to] you about [subject]. I am</p>sincerely sorry for letting the ball drop on this one—in the future, I’ll double-check that I’ve sent my messages to you so it doesn’t happen again.</p><p>After meeting with the Dev Ops team, we’ve decided to move forward with the original plan discussed at our March</p>meeting.</p><p>Apologies again,<br>Chris</p>"
    ]
};
